// Kommo agent — backfill leads from the Developers pipeline into the repo.
//
// Modes:
//   default       → inspect/dry-run (no writes, shows what would happen)
//   --apply       → actually create/update person.md and post Kommo notes
//
// Filters (per agreement with Gonzalo):
//   - Pipeline: "Developers" (NOT "Developers Linkedin")
//   - Skip statuses: "Closed - lost", "Not qualified"
//   - Recency: lead updated_at within last 4 months
//   - Skip auto-generated names ("Facebook №...", "Lead #...")
//   - Skip company-only leads (no contacts attached — those live in
//     another pipeline anyway)
//
// Side effects when --apply:
//   - Create or update /data/people/<slug>.md with Channel: kommo,
//     Kommo Lead ID, Kommo Contact ID, Phone, Email, etc.
//   - Create /data/companies/<slug>.md if a company is linked and
//     doesn't exist yet.
//   - Post ONE [Cobuildy OS] note in the Kommo lead saying it was
//     imported (so we can later filter agent-written notes from
//     human-written ones).

const path = require('path');
const fs   = require('fs');

require('dotenv').config({ path: path.join(__dirname, '../.env') });

const { addNote } = require('./kommo.js');
const { findPersonMatches, findCompanyMatches } = require('../entity/match.js');
const {
  PEOPLE_DIR, COMPANIES_DIR,
  today, slugify, setFields, readTemplate, buildPersonTitle,
  fillCompanyMd,
  updatePersonFields,
} = require('../entity/persist.js');

const TOKEN     = (process.env.KOMMO_TOKEN     || '').trim();
const SUBDOMAIN = (process.env.KOMMO_SUBDOMAIN || '').trim();
const BASE      = `https://${SUBDOMAIN}.kommo.com/api/v4`;

function getArg(name, defaultValue) {
  const idx = process.argv.indexOf(`--${name}`);
  if (idx >= 0 && idx + 1 < process.argv.length) return process.argv[idx + 1];
  return defaultValue;
}

const PIPELINE_NAME    = getArg('pipeline', 'Developers');
const SKIP_STATUSES    = new Set(['Closed - lost', 'Not qualified', 'Closed - won']);
const RECENCY_MONTHS   = 4;
const REQ_DELAY_MS     = 150;  // ~6.5 rps, safely under Kommo's ~7 rps limit

const apply = process.argv.includes('--apply');

// ── HTTP ──────────────────────────────────────────────────────────────────────

async function api(method, endpoint, body) {
  if (!TOKEN || !SUBDOMAIN) {
    throw new Error('KOMMO_TOKEN / KOMMO_SUBDOMAIN must be set in scripts/.env');
  }
  const res = await fetch(BASE + endpoint, {
    method,
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    throw new Error(`Kommo ${res.status} on ${method} ${endpoint}: ${await res.text()}`);
  }
  if (res.status === 204) return null;
  return res.json();
}

const sleep = ms => new Promise(r => setTimeout(r, ms));

// ── Helpers ───────────────────────────────────────────────────────────────────

function isAutoGeneratedName(name) {
  if (!name) return true;
  const n = name.trim();
  return /^facebook\s*[№#]/i.test(n) || /^lead\s*#?\d+$/i.test(n);
}

function isWithinRecency(unix) {
  const cutoff = Date.now() - RECENCY_MONTHS * 30 * 24 * 60 * 60 * 1000;
  return unix * 1000 >= cutoff;
}

function fmtUnixDate(unix) {
  return new Date(unix * 1000).toISOString().slice(0, 10);
}

async function findPipelineId(name) {
  const data = await api('GET', '/leads/pipelines');
  const p = (data._embedded?.pipelines || []).find(p => p.name === name);
  if (!p) throw new Error(`Pipeline "${name}" not found in Kommo`);
  return p.id;
}

async function getStatusMap(pipelineId) {
  const data = await api('GET', `/leads/pipelines/${pipelineId}`);
  const map = {};
  for (const s of data._embedded?.statuses || []) map[s.id] = s.name;
  return map;
}

async function* paginateLeads(pipelineId) {
  let page = 1;
  while (true) {
    const data = await api('GET',
      `/leads?filter[pipeline_id]=${pipelineId}&with=contacts,companies&page=${page}&limit=250`);
    const leads = data._embedded?.leads || [];
    if (leads.length === 0) return;
    for (const lead of leads) yield lead;
    if (leads.length < 250) return;
    page++;
    await sleep(REQ_DELAY_MS);
  }
}

async function getContactDetails(contactId) {
  return api('GET', `/contacts/${contactId}?with=companies`);
}

function findCustomField(values = [], { code, name }) {
  if (code) {
    const f = values.find(f => f.field_code === code);
    if (f) return f.values?.[0]?.value || '';
  }
  if (name) {
    const f = values.find(f => f.field_name === name);
    if (f) return f.values?.[0]?.value || '';
  }
  return '';
}

// Find a person.md whose `Kommo Lead ID` matches. Used for re-import
// idempotency: if we've already imported this lead, just refresh fields
// instead of re-creating (and risking another note in Kommo).
function findByKommoLeadId(leadId) {
  if (!fs.existsSync(PEOPLE_DIR)) return null;
  const files = fs.readdirSync(PEOPLE_DIR)
    .filter(f => f.endsWith('.md') && !f.startsWith('_template_'));
  const target = String(leadId);
  for (const file of files) {
    const text = fs.readFileSync(path.join(PEOPLE_DIR, file), 'utf8').replace(/\r\n/g, '\n');
    const m = text.match(/^- \*\*Kommo Lead ID:\*\*[ \t]*([^\n]*)$/m);
    if (m && m[1].trim() === target) return file.replace(/\.md$/, '');
  }
  return null;
}

// Disambiguate a slug against existing files. If `<baseSlug>.md` exists
// AND it's a DIFFERENT Kommo lead, append the Kommo Contact ID. This
// covers the case of two distinct people with the same first name (e.g.
// two "Javier" leads from Marquiz form submissions).
function safeSlug(baseSlug, contactId, leadId) {
  const personPath = path.join(PEOPLE_DIR, `${baseSlug}.md`);
  if (!fs.existsSync(personPath)) return baseSlug;
  const existing = fs.readFileSync(personPath, 'utf8').replace(/\r\n/g, '\n');
  const m = existing.match(/^- \*\*Kommo Lead ID:\*\*[ \t]*([^\n]*)$/m);
  const existingLeadId = m ? m[1].trim() : '';
  if (existingLeadId && existingLeadId === String(leadId)) return baseSlug;
  return `${baseSlug}-${contactId}`;
}

function summarizeContact(contact) {
  const cf = contact.custom_fields_values || [];
  return {
    id:        contact.id,
    name:      (contact.name || `${contact.first_name || ''} ${contact.last_name || ''}`).trim(),
    firstName: contact.first_name || '',
    lastName:  contact.last_name  || '',
    phone:     findCustomField(cf, { code: 'PHONE' }),
    email:     findCustomField(cf, { code: 'EMAIL' }),
    linkedin:  findCustomField(cf, { name: 'LinkedIn' }),
    position:  findCustomField(cf, { code: 'POSITION' }),
    company:   contact._embedded?.companies?.[0]?.name || null,
  };
}

// ── Person.md filler (kommo channel) ─────────────────────────────────────────

function fillPersonMdKommo(c, lead, statusName, companySlug, personSlug) {
  const date      = today();
  const firstSeen = fmtUnixDate(lead.created_at);
  const lastSeen  = fmtUnixDate(lead.updated_at);

  let text = readTemplate(path.join(PEOPLE_DIR, '_template_person.md'));
  const title = buildPersonTitle(c.name, { company: c.company, email: c.email, phone: c.phone });
  text = text.replace('# [Full Name]', `# ${title}`);
  text = setFields(text, {
    'Email':              c.email,
    'Phone':              c.phone,
    'WhatsApp':           c.phone,    // Kommo phones are typically WhatsApp
    'LinkedIn':           c.linkedin,
    'Kommo Lead ID':      String(lead.id),
    'Kommo Contact ID':   String(c.id),
    'Role':               'promoter',
    'Investor ID':        '',
    'Channel':            'kommo',
    'Language':           '',
    'First contact date': firstSeen,
    'Current stage':      'prospecting',
    'Last updated':       date,
    'Active projects':    '',
    'Last email':         '',
    'Last call':          '',
    'Last meet':          '',
    'Last LinkedIn':      '',
    'Last Kommo':         lastSeen,
    'Notes':              c.position ? `Position: ${c.position}` : '',
    'Projects':           '',
    'Log':                personSlug ? `/data/people/logs/${personSlug}.md` : '',
  });
  text = text.replace(
    /- \*\*Company:\*\* \[company_name\.md\]/,
    companySlug ? `- **Company:** [${companySlug}.md](/data/companies/${companySlug}.md)` : '- **Company:** '
  );
  text = text.replace(
    /- \*\*Company:\*\* \/data\/companies\/company_name\.md/,
    companySlug ? `- **Company:** /data/companies/${companySlug}.md` : '- **Company:** '
  );
  return text;
}

// ── Per-lead processing ──────────────────────────────────────────────────────

async function processLead(lead, statusName) {
  const log = (msg) => console.log(`  ${msg}`);
  console.log(`\n→ [${lead.id}] ${lead.name}  (${statusName}, updated ${fmtUnixDate(lead.updated_at)})`);

  // Idempotency: if this Kommo lead is already in the repo, refresh and
  // return — don't post another import note.
  const alreadyImported = findByKommoLeadId(lead.id);
  if (alreadyImported) {
    log(`i Already imported as ${alreadyImported} (Kommo Lead ID match)`);
    if (apply) {
      updatePersonFields(alreadyImported, {
        'Last Kommo':   fmtUnixDate(lead.updated_at),
        'Last updated': today(),
      });
      log(`↻ Refreshed Last Kommo on ${alreadyImported}.md`);
    } else {
      log(`(would refresh Last Kommo on ${alreadyImported}.md)`);
    }
    return { ok: alreadyImported, refresh: true };
  }

  // Each lead has one or more contacts. We process the first one
  // (multi-contact leads are rare; future improvement: handle all).
  const embeddedContacts = lead._embedded?.contacts || [];
  if (embeddedContacts.length === 0) {
    log('✗ No contacts attached — skipping');
    return { skipped: 'no contacts' };
  }

  const contactStub = embeddedContacts[0];
  await sleep(REQ_DELAY_MS);
  const contactFull = await getContactDetails(contactStub.id);
  const c = summarizeContact(contactFull);

  if (!c.name) {
    log('✗ Contact has no name — skipping');
    return { skipped: 'contact no name' };
  }
  if (!c.phone && !c.email) {
    log('✗ No phone or email — skipping');
    return { skipped: 'no phone/email' };
  }

  // Resolve company (if attached on the lead OR contact)
  const leadCompany    = lead._embedded?.companies?.[0]?.name;
  const contactCompany = c.company;
  const companyName    = leadCompany || contactCompany || null;
  let companySlug = null;

  if (companyName) {
    const matches = findCompanyMatches({ name: companyName });
    if (matches[0] && matches[0].confidence >= 90) {
      companySlug = matches[0].slug;
      log(`i Matched existing company ${companySlug}`);
    } else {
      companySlug = slugify(companyName);
      const cPath = path.join(COMPANIES_DIR, `${companySlug}.md`);
      if (apply && !fs.existsSync(cPath)) {
        fs.writeFileSync(cPath, fillCompanyMd(companyName, slugify(c.name), c.name, null));
        log(`✓ Created data/companies/${companySlug}.md`);
      } else if (!fs.existsSync(cPath)) {
        log(`(would create data/companies/${companySlug}.md)`);
      }
    }
  }

  // Resolve person
  const candidate = { name: c.name, email: c.email, phone: c.phone, company: companyName };
  const personMatches = findPersonMatches(candidate);
  const top = personMatches[0];
  const personSlug = (top && top.confidence >= 90)
    ? top.slug
    : safeSlug(slugify(c.name), c.id, lead.id);

  const personPath = path.join(PEOPLE_DIR, `${personSlug}.md`);

  if (top && top.confidence >= 90) {
    log(`i Matched existing person ${personSlug} (${top.confidence}% — ${top.reason})`);
    if (apply) {
      // Refresh Kommo IDs + contact info that might be missing
      updatePersonFields(personSlug, {
        'Kommo Lead ID':    String(lead.id),
        'Kommo Contact ID': String(c.id),
        'Last Kommo':       fmtUnixDate(lead.updated_at),
        'Last updated':     today(),
      });
      log(`↻ Refreshed Kommo IDs on ${personSlug}.md`);
    } else {
      log(`(would refresh Kommo IDs on ${personSlug}.md)`);
    }
  } else {
    if (apply) {
      fs.writeFileSync(personPath, fillPersonMdKommo(c, lead, statusName, companySlug, personSlug));
      log(`✓ Created data/people/${personSlug}.md`);
    } else {
      log(`(would create data/people/${personSlug}.md)`);
    }
  }

  // Tag the Kommo lead so future "import notes" runs know this one was
  // already touched by us. House rule: every agent-written note carries
  // the [Cobuildy OS] prefix.
  const noteText = `[Cobuildy OS] Lead imported into Cobuildy OS on ${today()}.\nDetalles en repo: /data/people/${personSlug}.md`;
  if (apply) {
    try {
      await sleep(REQ_DELAY_MS);
      await addNote(lead.id, noteText);
      log(`✓ Posted [Cobuildy OS] import note on Kommo lead ${lead.id}`);
    } catch (err) {
      log(`✗ Kommo addNote failed: ${err.message}`);
    }
  } else {
    log(`(would post [Cobuildy OS] note on Kommo lead ${lead.id})`);
  }

  return { ok: personSlug };
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log(`Mode: ${apply ? '⚡ APPLY (will write to repo and Kommo)' : '🔍 DRY RUN (no writes)'}\n`);

  console.log(`Finding pipeline "${PIPELINE_NAME}"...`);
  const pipelineId = await findPipelineId(PIPELINE_NAME);
  console.log(`Pipeline ID: ${pipelineId}`);

  const statusMap = await getStatusMap(pipelineId);
  console.log(`Statuses: ${Object.values(statusMap).join(', ')}\n`);

  // Pass 1: collect + filter
  let total = 0;
  const skipped = {};
  const toProcess = [];
  function bumpSkip(reason) { skipped[reason] = (skipped[reason] || 0) + 1; }

  for await (const lead of paginateLeads(pipelineId)) {
    total++;
    const statusName = statusMap[lead.status_id] || `unknown(${lead.status_id})`;
    if (SKIP_STATUSES.has(statusName))    { bumpSkip(`status: ${statusName}`); continue; }
    if (!isWithinRecency(lead.updated_at)) { bumpSkip('outside 4-month recency'); continue; }
    if (isAutoGeneratedName(lead.name))    { bumpSkip('auto-generated name'); continue; }
    if (!lead._embedded?.contacts || lead._embedded.contacts.length === 0) {
      bumpSkip('company-only (no contacts)');
      continue;
    }
    toProcess.push({ lead, statusName });
  }

  console.log(`Total leads in pipeline: ${total}`);
  console.log(`Filtered out:`);
  for (const [reason, count] of Object.entries(skipped)) {
    console.log(`  ${count.toString().padStart(4)}  ${reason}`);
  }
  console.log(`Survivors: ${toProcess.length}\n`);

  if (!apply) {
    console.log('--- Sample of what would be imported (first 15) ---');
    for (const { lead, statusName } of toProcess.slice(0, 15)) {
      console.log(`  [${lead.id}] ${lead.name} (${statusName}, updated ${fmtUnixDate(lead.updated_at)})`);
    }
    if (toProcess.length > 15) console.log(`  ... and ${toProcess.length - 15} more`);
    console.log('\nRe-run with --apply to actually write.');
    return;
  }

  // Pass 2: write
  let ok = 0, errs = 0, postSkipped = 0;
  for (const { lead, statusName } of toProcess) {
    try {
      const r = await processLead(lead, statusName);
      if (r.ok) ok++;
      else if (r.skipped) postSkipped++;
    } catch (err) {
      console.error(`  ✗ Error on lead ${lead.id}: ${err.message}`);
      errs++;
    }
  }

  console.log(`\n=== Done ===`);
  console.log(`  Imported / refreshed: ${ok}`);
  console.log(`  Skipped during processing (no contact, no info, etc.): ${postSkipped}`);
  console.log(`  Errors: ${errs}`);
}

main().catch(err => { console.error(err.message); process.exit(1); });
